account_number: ''
ai_confidence_threshold: 0.5
cb_timeout_sec: 3
cutoff_time: '14:00'
daily_stop_loss_limit: -100000.0
db_batch_size: 500
enable_cutoff: false
global_max_exposure: 50000000
global_max_loss: -500000
influx_bucket: stock_data
initial_balance: 10000000
kiwoom:
  rest_base_url:
    real: https://api.kiwoom.com
    virtual: https://mockapi.kiwoom.com
  trading_mode: real
  ws_url:
    real: wss://api.kiwoom.com:10000/api/dostk/websocket
    virtual: wss://mockapi.kiwoom.com:10000/api/dostk/websocket
live_trading_model_type: smart
log_level: DEBUG
max_buffer_size: 100000
max_invest_per_symbol: 300000.0
max_open_positions: 4
max_position_pct: 50.0
protected_symbols:
- '323410'
seq_len: 10
signal_only_mode: true
slippage: 0.0005
stop_loss_pct: -2.0
symbols:
- code: 000660_AL
  name: 에스케이하이닉스
- code: 001440_AL
  name: 대한전선
- code: 003280_AL
  name: 흥아해운
- code: 005290_AL
  name: 동진쎄미켐
- code: 005880_AL
  name: 대한해운
- code: 006340_AL
  name: 대원전선
- code: 006360_AL
  name: 지에스건설
- code: 006490_AL
  name: 인스코비
- code: 006910_AL
  name: 보성파워텍
- code: 007660_AL
  name: 이수페타시스
- code: 008350_AL
  name: 남선알미늄
- code: 009830_AL
  name: 한화솔루션
- code: 010140_AL
  name: 삼성중공업
- code: 010170_AL
  name: 대한광통신
- code: 010820_AL
  name: 퍼스텍
- code: 011000_AL
  name: 진원생명과학
- code: 011930_AL
  name: 신성이엔지
- code: 012200_AL
  name: 계양전기
- code: 017550_AL
  name: 수산세보틱스
- code: 017900_AL
  name: 광전자
- code: 018470_AL
  name: 조일알미늄
- code: 018880_AL
  name: 한온시스템
- code: 024740_AL
  name: 한일단조공업
- code: 027040_AL
  name: 서울전자통신
- code: 028050_AL
  name: 삼성이앤에이
- code: 032820_AL
  name: 우리기술
- code: 033230_AL
  name: 인성정보
- code: 034020_AL
  name: 두산에너빌리티
- code: 034220_AL
  name: LG디스플레이
- code: 036540_AL
  name: 에스에프에이반도체
- code: 036930_AL
  name: 주성엔지니어링
- code: 038110_AL
  name: 에코플라스틱
- code: 046120_AL
  name: 오르비텍
- code: 046970_AL
  name: 우리로
- code: 047040_AL
  name: 대우건설
- code: 049080_AL
  name: 기가레인
- code: 049480_AL
  name: 오픈베이스
- code: 050110_AL
  name: 캠시스
- code: 051980_AL
  name: 중앙첨단소재
- code: 060310_AL
  name: 삼에스코리아
- code: 065420_AL
  name: 에스아이리소스
- code: 069540_AL
  name: 빛과전자
- code: 077360_AL
  name: 덕산하이메탈
- code: 078590_AL
  name: 휴림에이텍
- code: 080220_AL
  name: 제주반도체
- code: 082740_AL
  name: 한화엔진 주식회사
- code: 082850_AL
  name: 우리바이오
- code: 090710_AL
  name: 휴림로봇
- code: 091970_AL
  name: 나노캠텍
- code: 092220_AL
  name: 케이이씨
- code: 093370_AL
  name: 후성
- code: 097230_AL
  name: 에이치제이중공업
- code: 099440_AL
  name: 스맥
- code: 131400_AL
  name: 이브이첨단소재
- code: 131760_AL
  name: 파인텍
- code: 137950_AL
  name: 제이씨케미칼
- code: 267320_AL
  name: 나인테크
- code: 332570_AL
  name: 피에스일렉트로닉스
- code: 336370_AL
  name: 솔루스첨단소재
- code: 403870_AL
  name: 에이치피에스피
- code: 417200_AL
  name: 엘에스머트리얼즈
- code: 460860_AL
  name: 동국제강
- code: 484590_AL
  name: 삼양컴텍
telegram_chat_id: '8338432975'
universe:
- code: 006340
  name: 대원전선
- code: '047040'
  name: 대우건설
- code: '011930'
  name: 신성이엔지
