db_batch_size: 500
global_max_exposure: 50000000
global_max_loss: -500000
initial_balance: 10000000
kiwoom:
  rest_base_url:
    real: https://openapi.kiwoom.com
    virtual: https://openapivts.kiwoom.com
  trading_mode: virtual
  ws_url:
    real: wss://api.kiwoom.com:10000/api/dostk/websocket
    virtual: wss://mockapi.kiwoom.com:10000/api/dostk/websocket
max_buffer_size: 10000
seq_len: 10
slippage: 0.0005
symbol: 005930
symbols:
- code: '014370'
  name: Stock_Company_1437
- code: 008000
  name: Stock_Company_800
- code: '017250'
  name: Stock_Company_1725
- code: '007140'
  name: Stock_Company_714
- code: 008090
  name: Stock_Company_809
- code: '002600'
  name: Stock_Company_260
- code: '003770'
  name: Stock_Company_377
- code: 000190
  name: Stock_Company_19
- code: '017470'
  name: Stock_Company_1747
- code: '007070'
  name: Stock_Company_707
- code: 001840
  name: Stock_Company_184
- code: 005690
  name: Stock_Company_569
- code: '006610'
  name: Stock_Company_661
- code: '012070'
  name: Stock_Company_1207
- code: '006120'
  name: Stock_Company_612
- code: 003830
  name: Stock_Company_383
- code: 018630
  name: Stock_Company_1863
- code: '017440'
  name: Stock_Company_1744
- code: 008800
  name: Stock_Company_880
- code: 000940
  name: Stock_Company_94
universe:
- code: 005930
  name: Samsung
- code: '000660'
  name: SK Hynix
- code: '035420'
  name: Naver
