account_number: ''
active_model_path: ./saved_models/random/model_advanced_random_best_fine.zip
ai_confidence_threshold: 0.5
cb_timeout_sec: 3
cutoff_time: '14:00'
daily_stop_loss_limit: -100000.0
db_batch_size: 500
enable_cutoff: false
global_max_exposure: 50000000
global_max_loss: -500000
influx_bucket: stock_data
initial_balance: 10000000
kiwoom:
  rest_base_url:
    real: https://api.kiwoom.com
    virtual: https://mockapi.kiwoom.com
  trading_mode: real
  ws_url:
    real: wss://api.kiwoom.com:10000/api/dostk/websocket
    virtual: wss://mockapi.kiwoom.com:10000/api/dostk/websocket
live_trading_model_type: smart
log_level: DEBUG
max_buffer_size: 100000
max_invest_per_symbol: 300000.0
max_open_positions: 4
max_position_pct: 50.0
protected_symbols:
- '323410'
seq_len: 10
signal_only_mode: true
slippage: 0.0005
stop_loss_pct: -2.0
symbols:
- code: 001440_AL
  name: 대한전선
- code: 003280_AL
  name: 흥아해운
- code: 006340_AL
  name: 대원전선
- code: 008350_AL
  name: 남선알미늄
- code: 009830_AL
  name: 한화솔루션
- code: 010140_AL
  name: 삼성중공업
- code: 010820_AL
  name: 퍼스텍
- code: 011930_AL
  name: 신성이엔지
- code: 036930_AL
  name: 주성엔지니어링
- code: 038110_AL
  name: 에코플라스틱
- code: 047040_AL
  name: 대우건설
- code: 077360_AL
  name: 덕산하이메탈
- code: 080220_AL
  name: 제주반도체
- code: 090710_AL
  name: 휴림로봇
- code: 093370_AL
  name: 후성
- code: 097230_AL
  name: 에이치제이중공업
- code: 131400_AL
  name: 이브이첨단소재
- code: 137950_AL
  name: 제이씨케미칼
telegram_chat_id: '8338432975'
universe:
- code: 3296
  name: 대원전선
- code: '047040'
  name: 대우건설
- code: 011930
  name: 신성이엔지
